name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: test "`uname -s`" = "Linux" -a -f /usr/bin/apt && sudo apt install libreadline-dev libsmbclient-dev || true
    - name: configure+make
      run: make -f Makefile.dist
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
